/**
 * Design-kit icons mapped to lucide-react (line style).
 * Import named icons from here for consistency across the app.
 */
import {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  BrainCircuit,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CirclePlus,
  CircleUser,
  Clock,
  Cloud,
  CloudDownload,
  CloudRain,
  CloudSun,
  CreditCard,
  Crop,
  Download,
  Droplets,
  Edit,
  Eye,
  EyeOff,
  Facebook,
  Flag,
  Instagram,
  Linkedin,
  Grid2x2,
  Handshake,
  Heart,
  ShieldCheck,
  History,
  Info,
  Layers,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Moon,
  MoreVertical,
  Pencil,
  Phone,
  Plus,
  Search,
  Settings,
  Sparkles,
  Sun,
  Trash2,
  TriangleAlert,
  User,
  UserPlus,
  Users,
  Wheat,
  Wifi,
  Wind,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

export type { LucideIcon };

/** All kit icons for the style-guide grid */
export const kitIcons: { name: string; Icon: LucideIcon }[] = [
  { name: "lock", Icon: Lock },
  { name: "plus-circle", Icon: CirclePlus },
  { name: "mail", Icon: Mail },
  { name: "info", Icon: Info },
  { name: "heart", Icon: Heart },
  { name: "check", Icon: Check },
  { name: "user", Icon: User },
  { name: "eye-off", Icon: EyeOff },
  { name: "trash", Icon: Trash2 },
  { name: "users", Icon: Users },
  { name: "grid", Icon: Grid2x2 },
  { name: "search", Icon: Search },
  { name: "phone", Icon: Phone },
  { name: "chevron-up-down", Icon: ArrowUpDown },
  { name: "chevron-left", Icon: ChevronLeft },
  { name: "chevron-right", Icon: ChevronRight },
  { name: "chevron-down", Icon: ChevronDown },
  { name: "download-cloud", Icon: CloudDownload },
  { name: "more-vertical", Icon: MoreVertical },
  { name: "calendar", Icon: Calendar },
  { name: "edit", Icon: Edit },
  { name: "x-circle", Icon: XCircle },
  { name: "user-plus", Icon: UserPlus },
  { name: "layers", Icon: Layers },
  { name: "wheat", Icon: Wheat },
  { name: "credit-card", Icon: CreditCard },
  { name: "crop", Icon: Crop },
  { name: "map-pin", Icon: MapPin },
  { name: "flag", Icon: Flag },
  { name: "menu", Icon: Menu },
  { name: "sparkles", Icon: Sparkles },
  { name: "droplet", Icon: Droplets },
  { name: "alert", Icon: TriangleAlert },
  { name: "cloud-rain", Icon: CloudRain },
  { name: "sun", Icon: Sun },
  { name: "cloud", Icon: Cloud },
  { name: "cloud-sun", Icon: CloudSun },
  { name: "moon", Icon: Moon },
  { name: "wind", Icon: Wind },
  { name: "settings", Icon: Settings },
  { name: "bell", Icon: Bell },
  { name: "eye", Icon: Eye },
  { name: "plus", Icon: Plus },
  { name: "x", Icon: X },
  { name: "download", Icon: Download },
  { name: "pencil", Icon: Pencil },
  { name: "alert-circle", Icon: AlertCircle },
  { name: "arrow-up", Icon: ArrowUp },
  { name: "arrow-down", Icon: ArrowDown },
  { name: "arrow-left", Icon: ArrowLeft },
  { name: "arrow-right", Icon: ArrowRight },
];

export {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  BrainCircuit,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CirclePlus,
  CircleUser,
  Clock,
  Cloud,
  CloudRain,
  CloudSun,
  CreditCard,
  Download,
  Droplets,
  Edit,
  Handshake,
  Heart,
  ShieldCheck,
  Eye,
  EyeOff,
  Facebook,
  Grid2x2,
  History,
  Instagram,
  Linkedin,
  Layers,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Moon,
  MoreVertical,
  Pencil,
  Phone,
  Plus,
  Search,
  Settings,
  Sun,
  Trash2,
  TriangleAlert,
  User,
  UserPlus,
  Users,
  Wheat,
  Wifi,
  Wind,
  X,
  XCircle,
};
